name: Pages

permissions:
  pages: write
  id-token: write

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/pages.yml'
      - 'geetest/**'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with:
          path: 'geetest/'
      - id: deployment
        uses: actions/deploy-pages@v4
